/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package _06_Interfaces;

import javax.swing.ImageIcon;

/**
 *
 * @author Danna Star
 */
public class Home extends javax.swing.JFrame {
    
    ImageIcon logoCompanyPic = new ImageIcon("Untitled-3.png");
    ImageIcon fondoPic = new ImageIcon("caption.jpg");
    ImageIcon peoplePic = new ImageIcon("people.png");
    ImageIcon bookPic = new ImageIcon("booking.png");
    ImageIcon inPic = new ImageIcon("in.png");
    ImageIcon outPic = new ImageIcon("out.png");
    ImageIcon recordPic = new ImageIcon("folder.png");
    ImageIcon helpPic = new ImageIcon("help.png");
    
    /**
     * Creates new form Welcome
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        logo.setIcon(logoCompanyPic);
        logo.setText("");
        imagenFondo.setIcon(fondoPic);
        imagenFondo.setText("");
        inLabel.setIcon(inPic);
        inLabel.setText("");
        outLabel.setIcon(outPic);
        outLabel.setText("");
        peopleLabel.setIcon(peoplePic);
        peopleLabel.setText("");
        bookLabel.setIcon(bookPic);
        bookLabel.setText("");
        helpLabel.setIcon(helpPic);
        helpLabel.setText("");
        recordLabel.setIcon(recordPic);
        recordLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        peopleLabel = new javax.swing.JLabel();
        bookLabel = new javax.swing.JLabel();
        inLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();
        recordLabel = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 240, 213));
        jPanel1.setForeground(new java.awt.Color(253, 240, 213));
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rage Italic", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 18, 31));
        jLabel2.setText("An Unique Experience");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 73));
        jLabel1.setText("MIYAKO HOTELS & RESORTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 560, 70));

        logo.setText("jLabel2");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 130, 120));

        jPanel3.setBackground(new java.awt.Color(120, 0, 0));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, 10));

        jPanel2.setBackground(new java.awt.Color(102, 155, 188));
        jPanel2.setForeground(new java.awt.Color(102, 155, 188));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 48, 73));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(253, 240, 213));
        jButton2.setText("Visualizar Reservas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, 40));

        jButton7.setBackground(new java.awt.Color(0, 48, 73));
        jButton7.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(253, 240, 213));
        jButton7.setText("Check-Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 220, 40));

        jButton8.setBackground(new java.awt.Color(0, 48, 73));
        jButton8.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(253, 240, 213));
        jButton8.setText("Visualizar Huespedes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 40));

        jButton9.setBackground(new java.awt.Color(0, 48, 73));
        jButton9.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(253, 240, 213));
        jButton9.setText("Ayuda");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 220, 40));

        jButton10.setBackground(new java.awt.Color(0, 48, 73));
        jButton10.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(253, 240, 213));
        jButton10.setText("Check-In");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 220, 40));

        jButton11.setBackground(new java.awt.Color(0, 48, 73));
        jButton11.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(253, 240, 213));
        jButton11.setText("Historial de Habitaciones");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 220, 40));

        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("jLabel3");
        jPanel2.add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 60, 60));

        peopleLabel.setText("jLabel3");
        jPanel2.add(peopleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 60));

        bookLabel.setText("jLabel3");
        jPanel2.add(bookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, 60));

        inLabel.setText("jLabel3");
        jPanel2.add(inLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 60, 60));

        outLabel.setText("jLabel3");
        jPanel2.add(outLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 60, 60));

        recordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recordLabel.setText("jLabel3");
        jPanel2.add(recordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1050, 180));

        imagenFondo.setFont(new java.awt.Font("Rage Italic", 0, 24)); // NOI18N
        imagenFondo.setText("jLabel2");
        jPanel1.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookLabel;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel inLabel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel outLabel;
    private javax.swing.JLabel peopleLabel;
    private javax.swing.JLabel recordLabel;
    // End of variables declaration//GEN-END:variables
}
