
package _06_Interfaces;

import _03_Classes.Room;
import _05_Validations.Validations;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Daniela Zambrano
 */
public class RoomRecord extends javax.swing.JFrame {
    
    ImageIcon logoCompanyPic = new ImageIcon("Untitled-3.png");
    ImageIcon fondoPic = new ImageIcon("mount-fuji-1346096_1280.jpg");

    /**
     * Creates new form RoomRecord
     */
    public RoomRecord() {
        initComponents();
        this.setLocationRelativeTo(null);
        logo.setIcon(logoCompanyPic);
        logo.setText("");
        imagenFondo.setIcon(fondoPic);
        imagenFondo.setText("");
        textTitle.setVisible(false);
        text.setVisible(false);
        textScroll.setVisible(false);
        roomTitle.setVisible(false);
        numRoomLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textScroll = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        searchButtom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        roomTitle = new javax.swing.JLabel();
        textTitle = new javax.swing.JLabel();
        numRoomLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numRoom = new javax.swing.JTextField();
        backButtom = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 650));
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(253, 240, 213));
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(120, 0, 0));
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1050, 10));

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 73));
        jLabel1.setText("MIYAKO HOTELS & RESORTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 140, 30));

        text.setEditable(false);
        text.setBackground(new java.awt.Color(102, 155, 188));
        text.setColumns(20);
        text.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        text.setForeground(new java.awt.Color(0, 0, 0));
        text.setRows(5);
        text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text.setMargin(new java.awt.Insets(5, 5, 5, 5));
        textScroll.setViewportView(text);

        jPanel1.add(textScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 750, 340));

        searchButtom.setBackground(new java.awt.Color(120, 0, 0));
        searchButtom.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        searchButtom.setForeground(new java.awt.Color(253, 240, 213));
        searchButtom.setText("Buscar");
        searchButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtomActionPerformed(evt);
            }
        });
        jPanel1.add(searchButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 120, 40));

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 48, 73));
        jLabel2.setText("Historial de Habitación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 750, 70));

        roomTitle.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        roomTitle.setForeground(new java.awt.Color(0, 48, 73));
        roomTitle.setText("N° Habitación:");
        jPanel1.add(roomTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 130, 30));

        textTitle.setFont(new java.awt.Font("Perpetua", 3, 24)); // NOI18N
        textTitle.setForeground(new java.awt.Color(0, 48, 73));
        textTitle.setText("Clientes anteriormente hospedados");
        jPanel1.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 400, 30));

        numRoomLabel.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        numRoomLabel.setForeground(new java.awt.Color(0, 48, 73));
        numRoomLabel.setText("100");
        jPanel1.add(numRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 50, 30));

        jPanel7.setBackground(new java.awt.Color(0, 48, 73));
        jPanel7.setForeground(new java.awt.Color(0, 48, 73));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(120, 0, 0));
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1050, 10));

        jLabel3.setFont(new java.awt.Font("Perpetua", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 240, 213));
        jLabel3.setText("Inserte el número de habitación");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, 30));

        numRoom.setBackground(new java.awt.Color(102, 155, 188));
        numRoom.setForeground(new java.awt.Color(0, 48, 73));
        numRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numRoomActionPerformed(evt);
            }
        });
        jPanel7.add(numRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 240, 40));

        backButtom.setBackground(new java.awt.Color(120, 0, 0));
        backButtom.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        backButtom.setForeground(new java.awt.Color(253, 240, 213));
        backButtom.setText("Atrás");
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });
        jPanel7.add(backButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 90, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1050, 100));

        logo.setText("jLabel2");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 130, 120));

        imagenFondo.setFont(new java.awt.Font("Rage Italic", 0, 24)); // NOI18N
        imagenFondo.setText("jLabel2");
        jPanel1.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1130, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numRoomActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        Home Inicio = new Home();
        Inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtomActionPerformed

    private void searchButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtomActionPerformed
        String roomNumber= numRoom.getText();
        Room auxRoom=null;
        Validations val=new Validations();
        boolean check;
        if (val.isRoom(roomNumber)){
            /*el dato ingresado es valid
            *funcion que busca roomNumber en el arbol binario*
            porende se puedebuscar la habitacion en el sistema
            //cuando se obtenga el nodon y el objeto se iguala a aux Room
            auxRoom=Home.Miyako.searchRoom();
            */
            check=true;
        }
        else{
            textTitle.setVisible(false);
            text.setVisible(false);
            textScroll.setVisible(false);
            roomTitle.setVisible(false);
            numRoomLabel.setVisible(false);
            check=false;
            JOptionPane.showMessageDialog(null, "Debe colocar el número correspondiente a la habitación para poder visualizar el historial de la misma.\nInténtelo nuevamente.", "Información", INFORMATION_MESSAGE);
        }
        if(auxRoom!=null){
            
        textTitle.setVisible(true);
        textScroll.setVisible(true);
        roomTitle.setVisible(true);

        numRoomLabel.setVisible(true);
        numRoomLabel.setText(roomNumber);

        text.setVisible(true);
        text.setText(auxRoom.getSummaryForRecord());
        
        }
        else if(check){
            JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna habitación con el número ingresado.\nInténtelo nuevamente.", "Información", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField numRoom;
    private javax.swing.JLabel numRoomLabel;
    private javax.swing.JLabel roomTitle;
    private javax.swing.JButton searchButtom;
    private javax.swing.JTextArea text;
    private javax.swing.JScrollPane textScroll;
    private javax.swing.JLabel textTitle;
    // End of variables declaration//GEN-END:variables
}
